[package]
name = "charasay"
version = "2.0.1"
authors = ["Latif Sulistyo <latifsulistyo.me@gmail.com>"]
edition = "2021"
description = "The future of cowsay ğŸ®! Colorful characters saying something ğŸ—¨ï¸."
repository = "https://github.com/latipun7/charasay"
license = "MIT"
readme = "readme.md"
keywords = ["cowsay", "print", "ansi"]
categories = [
  "command-line-utilities",
  "value-formatting",
  "text-processing",
  "visualization",
  "rendering",
]

[profile.release]
strip = "symbols"
lto = true
codegen-units = 1
opt-level = "s"

[[bin]]
name = "chara"

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
clap_complete = "4.3.1"
rust-embed = { version = "6.7.0", features = ["debug-embed"] }
textwrap = { version = "0.16.0", features = ["terminal_size"] }
unicode-width = "0.1.10"
regex = "1.8.4"
rand = "0.8.5"
strip-ansi-escapes = "0.1.1"
